package com.github.gustavobarbosab.imovies.presentation.screen.home

import androidx.compose.runtime.Immutable
import com.github.gustavobarbosab.imovies.common.presentation.UiState
import com.github.gustavobarbosab.imovies.presentation.screen.home.model.HomeMovieModel

/**
 * This file contains all the classes that represent the contract of the Home Screen.
 * - HomeScreenState: Represents the state of the screen.
 * - HomeIntent: Represents the intents that the screen can emit.
 * - HomeResult: Represents the results from the intents.
 * - HomeSideEffect: Represents the side effects generated by a intent and state.
 */
@Immutable
data class HomeScreenState(
    val topBannerMovies: UiState<List<HomeMovieModel>>,
    val popularMovies: UiState<List<HomeMovieModel>>,
    val topRatedMovies: UiState<List<HomeMovieModel>>,
    val upcomingMovies: UiState<List<HomeMovieModel>>
) {
    companion object {
        fun initialState() = HomeScreenState(
            topBannerMovies = UiState.Loading,
            popularMovies = UiState.Loading,
            topRatedMovies = UiState.Loading,
            upcomingMovies = UiState.Loading
        )
    }
}

sealed class HomeIntent {
    data object Init : HomeIntent()
    data class MovieClicked(val movie: HomeMovieModel) : HomeIntent()
    // TODO implement the load more
}

sealed class HomeActionResult {
    data class UpdateSection(
        val section: Section,
        val update: SectionUpdate
    ) : HomeActionResult()

    data class DoNothing(val internalReason: String? = null) : HomeActionResult()

    sealed class Section {
        data object TopBanner : Section()
        data object Popular : Section()
        data object TopRated : Section()
        data object Upcoming : Section()
    }

    sealed class SectionUpdate {
        data object Loading : SectionUpdate()
        data object Failure : SectionUpdate()
        data class Success(val movies: List<HomeMovieModel>) : SectionUpdate()
    }
}

sealed class HomeSideEffect {
    data class NavigateToMovieDetail(val movie: HomeMovieModel) : HomeSideEffect()
    data object LoadPopularFailure : HomeSideEffect()
    data object LoadTopBannerFailure : HomeSideEffect()
    data object LoadTopRatedFailure : HomeSideEffect()
    data object LoadUpcomingFailure : HomeSideEffect()
}